name: sabowsla_functions
description: A dart client library for the Sabowsla functions.
version: 0.0.2
homepage: 'https://sabowsla.com'
repository: 'https://github.com/sabowsla/sabowsla-flutter/tree/main/packages/sabowsla_functions'
documentation: 'https://sabowsla.com/docs/reference/dart/functions-invoke'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: '>=0.13.4 <2.0.0'
  yet_another_json_isolate: ^2.0.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.16.4

