# Recommended lints for Flutter apps, packages, and plugins.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - sized_box_for_whitespace
    - sort_child_properties_last
    - use_build_context_synchronously
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
    - use_super_parameters
    - use_colored_box
    - use_decorated_box
    - unnecessary_lambdas
    # - type_annotate_public_apis
    - require_trailing_commas
    - one_member_abstracts
    - avoid_dynamic_calls
    - always_declare_return_types
    - always_put_required_named_parameters_first
    # - directives_ordering
    - sort_constructors_first
    # - discarded_futures
    - avoid_redundant_argument_values
    - unnecessary_null_checks
    # - comment_references
    # - unnecessary_statements
    # - avoid_escaping_inner_quotes
    # - avoid_multiple_declarations_per_line
    # - avoid_positional_boolean_parameters
    # - avoid_void_async
    - always_use_package_imports
    # - cascade_invocations
    - cast_nullable_to_non_nullable
    - dangling_library_doc_comments
    # - join_return_with_assignment
    # - no_default_cases
    # - no_literal_bool_comparisons
    - noop_primitive_operations
    # - only_throw_errors
    # - prefer_asserts_with_message
    # - prefer_null_aware_method_calls
    # - sort_unnamed_constructors_first
    # - unnecessary_await_in_return
    # - unnecessary_parenthesis
    # - unnecessary_raw_strings
    - unnecessary_to_list_in_spreads
    # - use_late_for_private_fields_and_variables
    # - use_named_constants