name: sabowsla_storage
description: Dart client library to interact with Sabowsla Storage. Sabowsla Storage provides an interface for managing Files stored in Sabowsla Server, using ISAR database as your database.
version: 0.0.1
homepage: 'https://sabowsla.com'
repository: 'https://github.com/sabowsla/sabowsla-flutter/tree/main/packages/sabowsla_storage'
documentation: 'https://sabowsla.com/docs/reference/dart/storage-createbucket'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: '>=0.13.4 <2.0.0'
  http_parser: ^4.0.1
  mime: ^1.0.2
  retry: ^3.1.0
  meta: ^1.7.0

dev_dependencies:
  test: ^1.21.4
  lints: ^2.1.1
  path: ^1.8.2
